version: '3.8'                  # Version 3.8 is quite new and should work

services:
  app:                          # The name of the service, can be anything
    image: todo-backend-docker  # Declares which image to use
    build: .                    # Declares where to build if image is not found
    ports:                      # Declares the ports to publish
      - 3000:3000

# docker-compose up
# docker-compose up --build ::: for rebuilding
# docker-compose up -d ::: run app in the background 
# docker-compose down 